version: '3.8'
services:
  dev:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bash
    entrypoint: sh -c

  publish-package:
    image: python:3.10
    volumes:
      - ./:/app
    working_dir: /app