[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "django_encrypted_settings"
version = "0.1.0"
description = "A utility to store encrypt and decrypt django settings files in YAML using Ansible Vault encryption"
authors = ["Dan Brosnan <dpjbrosnan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
ruamel-yaml = "^0.18.6"
ansible-vault = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
